---
title: "ELO Feature"
author: "Andrew Couch"
date: "8/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Data Loading and Prep
```{r}
library(tidyverse)
library(elo)
library(plotly)

df <- read_csv("fighter_table.csv")

```

```{r}
# Create a head-to-head dataframe for elo modeling
elo_df <- df %>% 
  # Select fight pk, fighter, weight class, and results
  select(fight_pk, weight_class, fighter, res) %>% 
  # Join a sudo opponent table and filter out redundant data 
  inner_join(df %>% select(fight_pk, opponent = fighter)) %>% 
  filter(fighter != opponent) %>% 
  select(fight_pk, weight_class, fighter, opponent, res) %>% 
  # Remove the duplicated fights (a,b) and (b,a)
  arrange(fight_pk) %>% 
  group_by(fight_pk) %>% 
  slice(1) %>% 
  ungroup() %>% 
  # Convert the data to a long format
  pivot_longer(cols = c(fighter, opponent)) %>% 
  # Group by fighter and sort fighters' matches to match histroy 
  group_by(value) %>% 
  arrange(fight_pk) %>% 
  # Add a total fights feature for regression to the mean
  mutate(fight_num = row_number()) %>% 
  ungroup() %>% 
  # Add a flag where a fighter is on averag at the second half of their career
  mutate(start_regress = if_else(fight_num >= 4, "Last Half", "First Half")) %>% 
  select(-fight_num) %>% 
  # Convert the data back to head-to-head format
  pivot_wider(names_from = name, values_from = value)

elo_df
```
# Elo Modeling
```{r}
# Define elo model parameters 
elo_param <- crossing(k = seq(from = 1, to = 50, by = 1),
                           v_regress = seq(from = .1, to = .9, by = .1))


elo_param
```



```{r}
# Create a function that extracts the top n fighters 
get_top_players <- function(k, v_regress, n){
  
  elo <- elo.run(res~fighter + opponent + regress(start_regress, 1500, v_regress), data = elo_df, k = k)
  
  rank.teams(elo) %>% 
    as_tibble(rownames = "fighter") %>% 
    rename("ranking" = value) %>% 
    filter(ranking <= n)
  
}

# Extract the top 10 fighters from each elo model
top_fighters <- elo_param %>% 
  mutate(top_fighters = pmap(list(k, v_regress, 10), get_top_players)) %>% 
  unnest(top_fighters)

top_fighters
```

# Parameter Evaluation 

```{r}
# Evaluate how many times a fighter is in a specific rank
top_fighters %>% 
  count(ranking, fighter) %>% 
  arrange(ranking, n)
```


```{r}
# Evaluate how often a fighter is in the list top 10 list 
top_fighters %>% 
  count(fighter, sort = TRUE) %>% 
  ggplot(aes(n)) + 
  geom_density() + 
  geom_rug()
```
```{r}
# Evaluate how stable the ranking when tuning parameters 
# Looking for straight lines which indicates that the fighters are not changing rankings
top_fighters %>% 
  add_count(fighter, ranking) %>% 
  pivot_longer(cols = c(k, v_regress)) %>% 
  mutate(ranking = as.factor(ranking)) %>% 
  ggplot(aes(x = value, y = n, color = ranking, group = ranking)) + 
  geom_jitter(alpha = .1) +
  geom_smooth() + 
  geom_rug() + 
  facet_wrap(~name, scales = "free")
```

```{r}
# Use v_regress value of .5
# Choose K values between 25 and 35
top_fighters %>% 
  filter(v_regress == .5) %>% 
  mutate(ranking = as.factor(ranking)) %>% 
  ggplot(aes(x = k, y = fighter, fill = ranking)) + 
  geom_tile() + 
  theme_minimal()
```



```{r}
# Create function that extracts elo history
get_fight_history <- function(k, v_regress){
  
  elo_model <- elo.run(res~fighter + opponent + regress(start_regress, 1500, v_regress), data = elo_df, k = k)

  elo_res <- elo_model %>% as.data.frame() 
  
  fighter_a <- elo_res %>% 
    select_at(vars(contains(".A", ignore.case = FALSE))) %>% 
    rename_all(~str_replace(.x, ".A", "")) 
  
  
  fighter_b <- elo_res %>% 
    select_at(vars(contains(".B", ignore.case = FALSE), p.A, wins.A)) %>% 
    rename_all(~str_replace(.x, ".A|.B", "")) %>% 
    mutate(p = 1-p,
           wins = 1-wins)
  
  bind_rows(fighter_a, fighter_b)
}


# Extract elo history 
elo_history <- elo_param %>% 
  filter(v_regress == .5,
         between(k, 25, 35)) %>% 
  mutate(history = map2(k, v_regress, get_fight_history)) %>% 
  unnest(history)

elo_history
```

```{r}
# Examine elo distributions by each parameter pairing
# Increase k results in wider tails
elo_history %>% 
  unite("param", k:v_regress) %>% 
  ggplot(aes(x = elo, color = param)) + 
  geom_density() + 
  geom_rug() + 
  facet_wrap(~param, scales = "fixed") + 
  theme(legend.position = "none")
```
```{r, fig.height=15}
library(ggridges)
# Examine elo changes 
# Can see how parameters affect the amount of upsets
elo_history %>% 
  unite("param", k:v_regress) %>% 
  # Filter negative values because it is essentially double counting (wins and loss)
  filter(update >= 0) %>% 
  ggplot(aes(x = update, y = param, fill = param)) + 
  geom_density_ridges() +
  theme(legend.position = "none")
```


