---
title: "Data Tidying"
author: "Andrew Couch"
date: "8/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

df <- read_csv("fight_data_raw.csv")

```



```{r}
df %>% colnames() 
```


Select relevant fields and convert to correct data types.
```{r}
df <- df %>% 
  # Deselect fields that will not be used in the model
  select(-UFC_Page, -cards, -fights) %>% 
  # Convert field name to lower case
  rename_all(tolower) %>% 
  # Convert date
  mutate(date = as.Date(date, format = "%B %d, %Y")) %>% 
  # Convert fields to categorical variables
  mutate(fighter_1_fighter = as.factor(fighter_1_fighter),
         fighter_2_fighter = as.factor(fighter_2_fighter),
         method = as.factor(method),
         fighter_1_res = as.factor(fighter_1_res),
         fighter_2_res = as.factor(fighter_2_res),
         weight_class = as.factor(weight_class)) %>% 
  # Adjust percents 
  mutate(fighter_1_sig_strike_percent = fighter_1_sig_strike_landed / fighter_1_sig_strike_attempts,
         fighter_1_td_percent = fighter_1_td_landed / fighter_1_td_attempts,
         fighter_2_sig_strike_percent = fighter_2_sig_strike_landed / fighter_2_sig_strike_attempts,
         fighter_2_td_percent = fighter_2_td_landed / fighter_2_td_attempts) %>% 
  # If no attempts than percent will be 0 (may be adjusted to a not attempted variable)
  mutate_at(vars(contains("percent")), .funs = ~if_else(is.nan(.x) == TRUE, 0, .x)) %>% 
  # Convert rounds and round_finished
  mutate(time_format = str_extract(time_format, "\\d")) %>% 
  rename("rounds" = time_format) %>% 
  mutate(rounds  = as.factor(rounds),
         round_finished = as.factor(round_finished)) %>% 
  # Convert method
  separate(method, into = c("method"), sep = "-", extra = "drop") %>% 
  mutate(method = str_trim(method),
         method = as.factor(method)) %>% 
  # Convert weight_class
  mutate(gender = str_extract(weight_class, "Women")) %>% 
  mutate(gender = if_else(is.na(gender) == TRUE, "Men", gender)) %>% 
  mutate(weight_class = str_extract(weight_class, "\\w+weight")) %>% 
  mutate(weight_class = if_else(is.na(weight_class == TRUE), "Catchweight", weight_class)) %>% 
  unite("weight_class", c(gender, weight_class)) %>% 
  mutate(weight_class = as.factor(weight_class)) %>% 
  # Convert referee
  mutate(referee = if_else(is.na(referee) == TRUE, "Missing", referee)) %>% 
  mutate(referee = as.factor(referee)) %>% 
  # Convert rounds
  mutate(rounds = if_else(is.na(rounds) == TRUE, round_finished, rounds)) %>% 
  # Create a fight pk for future feature engineering 
  mutate(row_num = row_number()) %>% 
  arrange(desc(row_num)) %>% 
  mutate(fight_pk = row_number()) %>% 
  arrange(row_num) %>% 
  select(-row_num) 
  
```


# Create a fighter dataset 
```{r}

# Fighter 1 data 
df %>% 
  select(-fighter_2_fighter) %>% 
  rename_all(.funs = ~str_replace(.x, "fighter_1_", ""))
  

```



























